### ISSUE TITLE
Node device-ios won't start / stf_ios_support and stf-ios-provider out of sync

### ISSUE THREAD

**Issue by donmezburak** [DeviceFarmer/stf_ios_support#61]
Hello,
I run the repo and configured everything. However phone seems on stuck in preparing mode. This is the stf_device_ios log:

<img width="983" alt="Screen Shot 2020-09-07 at 09 54 00" src="https://user-images.githubusercontent.com/1921050/92357266-36c63c80-f0f0-11ea-9f94-2983ec18e91a.png">

This is the run log:

<img width="1546" alt="Screen Shot 2020-09-07 at 09 53 53" src="https://user-images.githubusercontent.com/1921050/92357253-3168f200-f0f0-11ea-8392-6c72f84a748e.png">

**Comment by donmezburak** [comment]
can someone help me please ?

**Comment by nanoscopic** [comment]
The only way I am aware that this would happen is if the stf-ios-provider repo is out of sync with stf_ios_suppor.

The way to fix this:

- `cd stf_ios_support`
- `make`
- `git pull`
- `cd repos/stf-ios-provider`
- `git pull`
- `export PATH="/usr/local/opt/node@12/bin:$PATH"`
- `npm install`

**Comment by nanoscopic** [comment]
Closing. Feel free to reopen if the above steps do not fix the issue.
