### ISSUE TITLE
Buffer() is deprecated in procs

### ISSUE THREAD

**Issue by romainlouvet** [DeviceFarmer/stf_ios_support#63]
After run ./run command I have this log in my proc file

`{"iserr":true,"line":"2020-09-08T14:13:12.286Z INF/provider 13534 [*] Receiving devEvent message from coordinator via tcp://127.0.0.1:7294","proc":"stf_ios_provider","time":"2020-09-08T16:13:12+02:00"}
{"iserr":true,"line":"(node:13534) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.","proc":"stf_ios_provider","time":"2020-09-08T16:13:12+02:00"}
{"iserr":true,"line":"2020-09-08T14:13:12.293Z INF/provider 13534 [*] Sending output to \"tcp://192.168.171.157:7270\"","proc":"stf_ios_provider","time":"2020-09-08T16:13:12+02:00"}
{"iserr":true,"line":"2020-09-08 16:13:12.299 ivf_pull[13539:4013330] Send data to nanomsg tcp://127.0.0.1:7879","proc":"ivf","time":"2020-09-08T16:13:12+02:00","uuid":"***de81"}
{"iserr":true,"line":"2020-09-08T14:13:12.301Z INF/provider 13534 [*] Receiving input from \"tcp://192.168.171.157:7250\"","proc":"stf_ios_provider","time":"2020-09-08T16:13:12+02:00"}`

I have no device available in my DeviceFarmer UI

nodeVersion: v14.8.0

**Comment by nanoscopic** [comment]
The deprecated usage does not, for me, affect the usability of the code. ( it still works )

I have though updated the code to avoid the deprecated usage: https://github.com/DeviceFarmer/stf-ios-provider/commit/69ffe37d43f841c7449bc85cd98ab8e00dfd6867
