### ISSUE TITLE
Faild to make by the latest commit 9769575917ca1817d64cc64eaf347d60c9ba713b

### ISSUE THREAD

**Issue by chaooe** [DeviceFarmer/stf_ios_support#64]
It faild to make. below is the make log

GIT_COMMIT="9769575917ca1817d64cc64eaf347d60c9ba713b" GIT_DATE="1599790950" GIT_REMOTE="git@github.com:DeviceFarmer/stf_ios_support.git" EASY_VERSION="1.0" /Applications/Xcode.app/Contents/Developer/usr/bin/make -C coordinator
go build -o ../bin/coordinator -ldflags "-X main.GitCommit=9769575917ca1817d64cc64eaf347d60c9ba713b -X main.GitDate=1599790950 -X main.GitRemote=git@github.com:DeviceFarmer/stf_ios_support.git -X main.EasyVersion=1.0" . 
# coordinator.go
./ports.go:102:29: undefined: usemuxdPort
./shutdown.go:70:19: not enough arguments in call to free_ports
        have (int, int, int, int, *PortMap)
        want (int, int, int, int, int, *PortMap)
make[1]: *** [../bin/coordinator] Error 2
make: *** [bin/coordinator] Error 2

**Comment by nanoscopic** [comment]
Corrected in https://github.com/DeviceFarmer/stf_ios_support/commit/3bb1a31c013059890ce3253ac00b76059dee37a9

**Comment by chaooe** [comment]
Yes. it's ok to make now by your commit 3bb1a31
