### ISSUE TITLE
Error while following steps in Readme file

### ISSUE THREAD

**Issue by mbilbiesi** [DeviceFarmer/stf_ios_support#65]
Hello; firstly thanks for all your participating to make this iOS support; I am currently trying to follow the steps of building the provider; based on the first phase **build-machine-setup > Step 4 `make clone`** ; I am getting the following error when i run the command; any idea what i am missing or what cause this issue.

![image](https://user-images.githubusercontent.com/16744683/93390164-8e417680-f86d-11ea-889a-c760696bd1db.png)

**Comment by mbilbiesi** [comment]
I was struggling to find the correct repos required; i found them and this issue is not relative anymore

**Comment by nanoscopic** [comment]
You shouldn't have to "find the correct repos required"; `make` / the Makefile is supposed to automatically clone the repos needed. I have updated the check-version script to not error out as it was doing in this case. https://github.com/DeviceFarmer/stf_ios_support/commit/6446fdf805aff9b80434837de74fc6f80bb842b1

**Comment by mbilbiesi** [comment]
@nanoscopic if I freshly clone the repo and use make; i will get the result shown in the screenshot above; I am using IOS Catalina; i tried to hit the command with `sudo make` and `make` and both with same result !
