### ISSUE TITLE
Errors from IVF; avoid me to run

### ISSUE THREAD

**Issue by mbilbiesi** [DeviceFarmer/stf_ios_support#66]
Hello, I followed the steps to build the provider and after hit './run' i am getting the following results but i can't see anything on STF server; i believe it is not correctly running after seeing that IVF is attempting to connect 
![image](https://user-images.githubusercontent.com/16744683/93631885-a7246600-f9ec-11ea-8643-ff50bec1035c.png)

and looking into log for `ivf` proc; i got the following 
`2020-09-18 21:24:35.993 ivf_pull[44258:737564] Send data to nanomsg tcp://127.0.0.1:7879
2020-09-18 21:24:36.004 ivf_pull[44256:737460] device with udid 'XXXXXXX-XXXXXXXC32802E' not found
2020-09-18 21:24:46.017 ivf_pull[44261:737683] Send data to nanomsg tcp://127.0.0.1:7881
2020-09-18 21:24:46.040 ivf_pull[44258:737564] device with udid 'XXXXXXXX-XXXXXXX89002E' not found`

Any hints you can provide that helps me to debug and check each component is running correctly ?

**Comment by mbilbiesi** [comment]
Duplicated - > https://github.com/DeviceFarmer/stf_ios_support/issues/59

**Comment by nanoscopic** [comment]
Updated ios_avf_pull to check both dashed and non-dashed UDID. Please try again with the updated code: https://github.com/DeviceFarmer/ios_avf_pull/commit/f61e3780ffecb41e679f684a777f7c856908324e
