### ISSUE TITLE
I configured WebDriverAgent.xcodeproj with my certification, but `make` fails

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf_ios_support#68]
When I `make` after setting all certificates and configurations.

```
error: No account for team "44444444xxx". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any **iOS App Development** provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
error: No account for team "44444444xxx". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "44444444xxx" with a private key was found. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
```

Can you confirm that if I have "iPhone Developer" in my certificate and should work, because in the error log it says `couldn't find any iOS App Development`
```
$security find-identity -v -p codesigning
  1) x0x0x0x0x0x0x0x0x0x0xx0x0x0x0x0x0x0x0x0x0x "iPhone Developer: Jay111 (44444444xxx)"
  2) yoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyoyo "Apple Development: Jay111 (44444444xxx)"
```

Do I need to have `iOS App Development` in the reulst of `security find-identity -v -p codesigning`?

**Comment by gkrananth** [comment]
yes its required Apple Developer Account.

**Comment by nanoscopic** [comment]
The following command can be used to show the subject of your developer account:
`security find-identity -v -p codesigning | head -1 | cut -d\  -f 5-`

The following command be be used to then show the OU of your developer account:
`security find-certificate -p -c [subject from previous command] | openssl x509 -noout -subject | tr '/' '\n' | grep OU=`

What is needed in `config.json` is the OU, not the bit in () within the subject.
