### ISSUE TITLE
missing ios_video_enabler repos cause make failed

### ISSUE THREAD

**Issue by chaooe** [DeviceFarmer/stf_ios_support#77]
using the latest commit https://github.com/DeviceFarmer/stf_ios_support/commit/219146dd4b218e87f934599630839a55d411a000
make: *** No rule to make target `repos/ios_video_enabler/main.m', needed by `repos/ios_video_enabler/video_enabler'.  Stop.

**Comment by github-june** [comment]
Had the same problem

**Comment by chaooe** [comment]
Waiting for that repos push its commit.

**Comment by chaooe** [comment]
It has fixed
