### ISSUE TITLE
I can provider a more fast wda for click event, press event than appium/webdriveragent 

### ISSUE THREAD

**Issue by Richard1ybb** [DeviceFarmer/stf_ios_support#81]

**Comment by nanoscopic** [comment]
The currently used WDA click uses XCTest private API synthesize event. You are saying there is some way faster than that?

I agree that the synthesized event could be created in a less roundabout way than the code in WDA... should be able to skip the dumping of the on screen elements which is the main lag...

??

**Comment by nanoscopic** [comment]
This looks like spam to me. If you have some information here besides "I can do better than you" then add it or go away.
