### ISSUE TITLE
WARNING: Project essentially unmaintained.

### ISSUE THREAD

**Issue by nanoscopic** [DeviceFarmer/stf_ios_support#82]
This project, stf_ios_support, only came into being because TMobile gave permission for its development from day one to be fully open source. I am the sole creator, developer, and maintainer of the project. I essentially worked on this project fulltime as my main project at TMobile for about a year with them.

The project was contributed / shifted namespaces from github.com/tmobile to github.com/devicefarmer , in the hope of merging it with the upstream project ( previously OpenSTF ), during its transition away from Headspin ( which dissolved ). I believe that it still remains a goal of the other members of the DeviceFarmer project/namespace to merge IOS support and maintain this, but no one besides me so far has yet contributed to maintaining the project. A few members of the community have responded to some tickets and attempted to help others who have issues, but I don't see anyone stepping up currently to maintain the project more seriously.

TMobile terminated my position due to me being on the autistic spectrum ( with no process or discussion; which is illegal... ), so I am no longer working on this project full time. I won't be contributing to the open source project ( as much ) from here on out because I refuse to do anything to assist such a terrible company as TMobile. This project is likely to fall apart and go into "unmaintained" land as a result, since I am the sole contributor and only person who ever worked on it besides minor contributions.

I will continue to respond to tickets as I have free time and desire to do so, but since I am no longer being paid to support this project full-time, I won't be putting serious effort into doing so myself.

I am going to continue developing tooling and software to support remotely controlling IOS devices well, but the majority of my work from here will be done closed source primarily for the benefit of companies that are paying me to assist them.

The first thing I will be creating in that fashion is a new method of video streaming to resolve all the problems with the video streaming methods up till now. I will be releasing it as an app on the Apple store that anyone can purchase and use. The app will support being connected to stf_ios_support, and I will contribute code to the project to make that possible ( as an option so that there will always be the other free methods of video streaming ). The app will not be expensive, so I don't believe that this should hamper the continued open source usage and maintenance by others. I already have this described app working solidly streaming video from 4 devices simultaneously through one MacOS machine. It resolves many issues that are present with the currently open sourced video methods.

The second thing I will be creating is a replacement for OpenSTF server entirely. It will be streamlined to IOS usage. The purpose of this replacement:

1. To avoid having to bring OpenSTF sourcecode to a modern maintainable state. I spent quite a bit of effort working to do that, and it can still happen, but it is much more effective and reasonable to replace OpenSTF server than to fix it.

2. To make it much easier / possible / reasonable to address all the shortcomings of the way OpenSTF functions. I won't bother listing out the issues but I can assure you that the new software will work much better for IOS devices than the stf_ios_support integration with OpenSTF does.

3. To get away from ever having to use NodeJS. I've never been a fan of NodeJS, and if I'm not being paid full-time to support a NodeJS project, I would never touch it. I think NodeJS is terrible. The new replacement I am writing will be written in GoLang.

4. To make a profitable path for myself for continuing to work on IOS remote control ability. While there are a few companies willing to pay me part time for my work on stf_ios_support, their pay is not equal to what I was getting full-time with TMobile, and I won't be able to pay my bills through it. The only way I can continue to make an affordable way to control IOS devices is to go the closed-source path.

I will not take any action to harm the DeviceFarmer project or stf_ios_support repo and its related pieces. I wish the projects well and will continue to assist as I feel motivated to do so. The main purpose of this ticket is to inform the community of what is going on. Hopefully this will motivate others to step up and volunteer to help maintain the project. I welcome anyone willing to do so and will happily pass on my knowledge to them.

Feel free to use this ticket for discussion about how to move forward and keep the project going / advancing.

Finally, if a major company has plans to use this project seriously and is willing to hire me full time to continue development of it with a focus on making it work the way your company needs, then feel free to hire me. Despite my dislike for TMobile for their mishandling of the situation, and the illegality of their actions, I would be willing to continue the open source development if I am able to have a full-time job doing so.

**Comment by nanoscopic** [comment]
Good news on this front. I am in process of securing additional employment related to this project. This will enable me to continue supporting this project more than seemed possible.

**Comment by mbilbiesi** [comment]
> Good news on this front. I am in process of securing additional employment related to this project. This will enable me to continue supporting this project more than seemed possible.

It is really a very good news for this community ! Glad to hear that ! Looking forward to go farther with this project.

Thanks for the heads up ! all the support !

**Comment by nanoscopic** [comment]
Closing this ticket in favor of a new pinned notice about the status of this repo and the direction of the project overall.
