### ISSUE TITLE
Error "'AVCaptureDeviceDiscoverySession' is unavailable: not       available on macOS" when running `make`

### ISSUE THREAD

**Issue by NguyenHoangDuy2406** [DeviceFarmer/stf_ios_support#86]
Hi everyone,

I'm following the post https://github.com/DeviceFarmer/stf_ios_support, and staying at some last steps in **Build provider files**. But when running the cli `make`, an error show below:
<img width="581" alt="error" src="https://user-images.githubusercontent.com/1097668/99377443-c9f1ce80-28f8-11eb-9675-2b798c86332e.png">

I'm stuck there and can't continue, can anyone advise me for it ?

Thank you so much!

**Comment by nanoscopic** [comment]
https://developer.apple.com/documentation/avfoundation/avcapturedevicediscoverysession

Availability: MacOS 10.15+
Are you running MacOS < 10.15 ?

**Comment by NguyenHoangDuy2406** [comment]
> https://developer.apple.com/documentation/avfoundation/avcapturedevicediscoverysession
> 
> Availability: MacOS 10.15+
> Are you running MacOS < 10.15 ?

Really really thanks for the answering. That maybe the root cause of its error. (My MacOS is 10.14.x)
I'm not familiar with iOS and MacOS environment , so I miss that.

Thank you so much, nanoscopic ^^ and have a nice day
