### ISSUE TITLE
Error when execute "./run"

### ISSUE THREAD

**Issue by NguyenHoangDuy2406** [DeviceFarmer/stf_ios_support#90]
```
FATA[0001] ZMQ binding error                             coro=pub err="bind error" type=err_zmq zmq_spec="tcp://127.0.0.1:7294"

INFO[0001] Process start - device_trigger                binary=bin/osx_ios_device_trigger proc=device_trigger type=proc_start

E: 20-11-30 12:22:08 [97020]dangling 'REP' socket created at /Users/c001050/Documents/stf_ios_support/coordinator/zmq.go:336
E: 20-11-30 12:22:08 [97020]dangling 'PUB' socket created at pB?:28
E: 20-11-30 12:22:08 [97020]dangling 'PULL' socket created at :152
```

When I execute `./run`, the above error is displayed.
As my thinking, when I do at step 4: Have Xcode setup the "developer image" on your IOS device:
  Open Xcode
  Go to Windows... Devices and Simulators
  Wait while Developer Image is installed to your phone

But nothing was installed on my iPhone. I don't know is it effect to this issue or not.

Could everyone help me to resolve it? 

Thanks.

**Comment by mbilbiesi** [comment]
I used to have similar behavior, and when it happens i go manually kill processes related !!
I have no clue what is the root cause, but maybe you need to consider the following and it could help:
- Unplug/plug the devices 
- kill all processes related to stf-ios-support 
- make sure you are having full access for the user you are having !

**Comment by NguyenHoangDuy2406** [comment]
It's absolutely that I need.

Thank you so much! ^^

**Comment by vu1999** [comment]
Hi there! i still don't know how to deal with this issue! I do all things above but it doesn't work. Any help pls?  "Wait while Developer Image is installed to your phone" nothing happens for me!

**Comment by nanoscopic** [comment]
This error ```FATA[0001] ZMQ binding error                             coro=pub err="bind error" type=err_zmq zmq_spec="tcp://127.0.0.1:7294"``` means that port 7294 cannot be bound to on your machine.

The port 7294 is used by coordinator itself. What this means is that you likely have an instance of coordinator already running on your machine. Run `killall coordinator` to kill it and try again.

**Comment by nanoscopic** [comment]
The "developer image" is not something you will notice as being installed on your phone offhand. I think that it does add some additional options in the Settings of the iOS device but I have not paid attention to see what exactly it adds there.

Any device which you deploy apps to through Xcode must have the "developer image deployed". This is done automatically the first time you build and run an app on your iOS device through Xcode. So long as that was done once at some time it was already done.

It is very likely your iOS device already has the "developer image" on it. All you need to do is click the device in the Devices and Simulators list. If it didn't have it already it would show it being installed there. If no message about installing it appears there, it is already done.
