### ISSUE TITLE
Stuck at "Preparing" status when start "./run"

### ISSUE THREAD

**Issue by vu1999** [DeviceFarmer/stf_ios_support#92]
i have run "./run" but devices on STF dashboard keep "stucking" at Preparing Status
i get log "./view_log -proc stf_device_ios":
![Screen Shot 2020-12-30 at 15 42 30](https://user-images.githubusercontent.com/48922153/103340057-bfa91f80-4ab5-11eb-93d3-6d11ff721dea.png)
this is my config.json
![Screen Shot 2020-12-30 at 15 45 26](https://user-images.githubusercontent.com/48922153/103340284-41994880-4ab6-11eb-9e8c-6e1fbd33b7f3.png)

So what i need to do now :((

**Comment by vu1999** [comment]
i found what happened! in display.js, refactor s = fs

**Comment by nanoscopic** [comment]
So it is! https://github.com/DeviceFarmer/stf-ios-provider/blob/master/lib/units/device-ios/util/display.js#L51

Good catch. Thank you. This will be corrected shortly.

**Comment by nanoscopic** [comment]
Corrected in https://github.com/DeviceFarmer/stf-ios-provider/commit/d2b75529edd5e1722c369e45fe096aa6690c615c
