### ISSUE TITLE
Setup unsuccessful on managed Mac

### ISSUE THREAD

**Issue by himanshunamdeo** [DeviceFarmer/stf_ios_support#93]
Hi,
I am trying to setup STF iOS on my organisation managed Mac, but after running ./init on terminal the process is stopping after giving following warnings:

Could not fix pkgconfig for libplist; could not locate installed pc file in Cellar
Could not fix pkgconfig for libusbmuxd; could not locate installed pc file in Cellar.

Below are the terminal logs: 

vivek1.sinha@A356KMLZYA6LUYA stf_ios_support % ./init.sh
Xcode 12.0 installed
find: /usr/local/Cellar: No such file or directory
Installing missing packages:
  jq
  graphicsmagick
  zeromq
  protobuf
  yasm
  pkg-config
  carthage
  automake
  autoconf
  libtool
  wget
  go
  node@12
  libsodium
  czmq
  jpeg-turbo
  nanomsg
  libgcrypt
  gnutls
  mobiledeviceUpdating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from bca4804a9 to f7a718c1f.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
aliddns                       cloudflare-wrangler           crane                         hexo                          luv                           nuclei                        parliament                    vsh
ansible@2.9                   cpplint                       crcany                        ko                            msc-generator                 osmcoastline                  vitess
==> Updated Formulae
Updated 543 formulae.
==> Renamed Formulae
prest -> prestd
==> New Casks
brewlet                                         kieler                                          pokemon-trading-card-game-online                ptpwebcam                                       spotter
f-bar                                           lightkey                                        prezi-video                                     signet
==> Homebrew was updated to version 2.7.5
The changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/2.7.5
Warning: jq 1.6 is already installed and up-to-date.
To reinstall 1.6, run:
  brew reinstall jq
Warning: graphicsmagick 1.3.36 is already installed and up-to-date.
To reinstall 1.3.36, run:
  brew reinstall graphicsmagick
Warning: protobuf 3.14.0 is already installed and up-to-date.
To reinstall 3.14.0, run:
  brew reinstall protobuf
Warning: yasm 1.3.0_2 is already installed and up-to-date.
To reinstall 1.3.0_2, run:
  brew reinstall yasm
Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
Warning: automake 1.16.3 is already installed and up-to-date.
To reinstall 1.16.3, run:
  brew reinstall automake
Warning: autoconf 2.69 is already installed and up-to-date.
To reinstall 2.69, run:
  brew reinstall autoconf
Warning: libtool 2.4.6_2 is already installed and up-to-date.
To reinstall 2.4.6_2, run:
  brew reinstall libtool
Warning: node@12 12.20.1 is already installed and up-to-date.
To reinstall 12.20.1, run:
  brew reinstall node@12
Warning: libsodium 1.0.18_1 is already installed and up-to-date.
To reinstall 1.0.18_1, run:
  brew reinstall libsodium
Warning: czmq 4.2.0 is already installed and up-to-date.
To reinstall 4.2.0, run:
  brew reinstall czmq
Warning: jpeg-turbo 2.0.6 is already installed, it's just not linked.
To link this version, run:
  brew link jpeg-turbo
Warning: nanomsg 1.1.5 is already installed and up-to-date.
To reinstall 1.1.5, run:
  brew reinstall nanomsg
Warning: libgcrypt 1.8.7_1 is already installed and up-to-date.
To reinstall 1.8.7_1, run:
  brew reinstall libgcrypt
Warning: gnutls 3.6.15 is already installed and up-to-date.
To reinstall 3.6.15, run:
  brew reinstall gnutls
Warning: mobiledevice 2.0.0 is already installed and up-to-date.
To reinstall 2.0.0, run:
  brew reinstall mobiledevice
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/zeromq-4.3.4.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Pouring zeromq-4.3.4.catalina.bottle.tar.gz
🍺  /Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar/zeromq/4.3.4: 83 files, 6.0MB
Removing: /Users/vivek1.sinha/Library/Caches/Homebrew/zeromq--4.3.3_1.catalina.bottle.tar.gz... (1.6MB)
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/carthage-0.36.1.catalina.bottle.tar.gz
######################################################################## 100.0%
Error: carthage 0.36.0 is already installed
To upgrade to 0.36.1, run:
  brew upgrade carthage
Warning: Building wget from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master)
==> Downloading https://ftp.gnu.org/gnu/wget/wget-1.21.1.tar.gz
######################################################################## 100.0%
Warning: Your Xcode (12.0) is outdated.
Please update to Xcode 12.3 (or delete it).
Xcode can be updated from the App Store.

Error: wget 1.21 is already installed
To upgrade to 1.21.1, run:
  brew upgrade wget
Warning: Building go from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master)
==> Cloning https://go.googlesource.com/tools.git
Updating /Users/vivek1.sinha/Library/Caches/Homebrew/go--gotools--git
==> Checking out branch release-branch.go1.15
Already on 'release-branch.go1.15'
Your branch is up to date with 'origin/release-branch.go1.15'.
HEAD is now at c1934b75 go/analysis: improve error message for string(int) warning
==> Downloading https://storage.googleapis.com/golang/go1.7.darwin-amd64.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/ad0901a23a51bac69b65f20bbc8e3fe998bc87a3be91d0859ef27bd1fe537709--go1.7.darwin-amd64.tar.gz
==> Downloading https://golang.org/dl/go1.15.7.src.tar.gz
==> Downloading from https://dl.google.com/go/go1.15.7.src.tar.gz
######################################################################## 100.0%
Warning: Your Xcode (12.0) is outdated.
Please update to Xcode 12.3 (or delete it).
Xcode can be updated from the App Store.
Error: go 1.15.6 is already installed
To upgrade to 1.15.7, run:
  brew upgrade go
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
==> Reinstalling 1 broken dependent from source:
czmq
Warning: Building python@3.9 from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master)
==> Downloading https://files.pythonhosted.org/packages/94/23/e9e3d96500c063129a19feb854efbb01e6ffe7d913f1da8176692418ab8e/setuptools-51.1.1.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/dfd0f93bf21fd28ac8eb7b31b8c29e4ceee4eaf1026de0be1933c133d13f4100--setuptools-51.1.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ca/1e/d91d7aae44d00cd5001957a1473e4e4b7d1d0f072d1af7c34b5899c9ccdf/pip-20.3.3.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/20a3d55b9c92b83b2c00924c174145efd31ccbe94b8f91f40cffc61441e7b6f2--pip-20.3.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ed/46/e298a50dde405e1c202e316fa6a3015ff9288423661d7ea5e8f22f589071/wheel-0.36.2.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/2628149c388cda23d833947d9d838f27eba9442101b2958948fbe661e96b689b--wheel-0.36.2.tar.gz
==> Downloading https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/4f82a87872361431c1ff89331abe8b4474053a6310159862948c4e0f35bdaca5--Python-3.9.1.tar.xz
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/boost-1.75.0_1.catalina.bottle.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/40ef37d60bec8ad90d35d65aff8c1ed9d82ddbfec3fde186fb5741f1a868bde3--boost-1.75.0_1.catalina.bottle.tar.gz
Warning: Building source-highlight from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/vivek1.sinha/Work/Tools/Brew/brew-master)
==> Downloading https://ftp.gnu.org/gnu/src-highlite/source-highlight-3.1.9.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/66799b95504cab9499e2106e86a2b8bfe453bd612fab005d91ca073b970c0b18--source-highlight-3.1.9.tar.gz
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/asciidoc-9.0.5.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/docbook-xsl-1.79.2_1.catalina.bottle.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/e7f6b56b5d9b056039b8075b3c0d0bc5e808bf15614dfba3ef6cfd5fd2e659fa--docbook-xsl-1.79.2_1.catalina.bottle.tar.gz
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/gnu-getopt-2.36.1.catalina.bottle.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/3a2b0d395a8c5844980a8cf06773042c382f6853ca9e9b4f4ee79c6ff5ae5f11--gnu-getopt-2.36.1.catalina.bottle.tar.gz
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/xmlto-0.0.28.catalina.bottle.2.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/6605d13c2754b68a160abe2bed00b2a0dc31aba4d09deff82dbb96ce93ff56cf--xmlto-0.0.28.catalina.bottle.2.tar.gz
==> Downloading https://github.com/zeromq/czmq/commit/ace06a41da51b1196eef411669343cdf7e8665e2.patch?full_index=1
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/81276a751e3083aa86f47e078f590ba30f5e443e9004d0453ddd33e7bd365598--ace06a41da51b1196eef411669343cdf7e8665e2.patch
==> Downloading https://github.com/zeromq/czmq/commit/0c7cac3be12707225d03888a6047e5133d926751.patch?full_index=1
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/4a1ac91e4cd12935193c36c268af845d252903d5372e8c224e38e04bebba0209--0c7cac3be12707225d03888a6047e5133d926751.patch
==> Downloading https://github.com/zeromq/czmq/releases/download/v4.2.0/czmq-4.2.0.tar.gz
Already downloaded: /Users/vivek1.sinha/Library/Caches/Homebrew/downloads/79a01f3d781e9a327c6e5bdc2e523f2edf11cd10ecec9e80aceff360abbd70b5--czmq-4.2.0.tar.gz
==> Reinstalling czmq 
Warning: Your Xcode (12.0) is outdated.
Please update to Xcode 12.3 (or delete it).
Xcode can be updated from the App Store.

==> Installing dependencies for czmq: python@3.9, boost, source-highlight, asciidoc, docbook-xsl, gnu-getopt and xmlto
==> Installing czmq dependency: python@3.9
Warning: Your Xcode (12.0) is outdated.
Please update to Xcode 12.3 (or delete it).
Xcode can be updated from the App Store.

==> ./configure --prefix=/Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar/python@3.9/3.9.1_6 --enable-ipv6 --datarootdir=/Users/vivek1.sinha/Work/Tools/Brew/brew-master/Cellar/python@3.9/3.9.1_6/share --datadir=/Users/vivek1.sinha/Wo
Last 15 lines from /Users/vivek1.sinha/Library/Logs/Homebrew/python@3.9/01.configure:
checking for dup2... yes
checking for strdup... yes
checking for getpgrp... yes
checking for setpgrp... (cached) yes
checking for library containing crypt... none required
checking for library containing crypt_r... no
checking for crypt_r... no
checking for clock_gettime... yes
checking for clock_getres... yes
checking for clock_settime... yes
checking for major... yes
checking for getaddrinfo... yes
checking getaddrinfo bug... yes
Fatal: You must get working getaddrinfo() function.
       or you can specify "--disable-ipv6".
Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
python@3.9: update pip, setuptools https://github.com/Homebrew/homebrew-core/pull/69668
Test and build failures found during python 3.9 testing https://github.com/Homebrew/homebrew-core/issues/66450

Error: Your Xcode (12.0) is outdated.
Please update to Xcode 12.3 (or delete it).
Xcode can be updated from the App Store.

libplist - Installing HEAD
Updating Homebrew...
Warning: libplist HEAD-275cecd is already installed and up-to-date.
To reinstall HEAD, run:
  brew reinstall libplist
Could not fix pkgconfig for libplist; could not locate installed pc file in Cellar
libusbmuxd - Installing HEAD
Warning: libusbmuxd HEAD-c56e112 is already installed and up-to-date.
To reinstall HEAD, run:
  brew reinstall libusbmuxd
Could not fix pkgconfig for libusbmuxd; could not locate installed pc file in Cellar

**Comment by nanoscopic** [comment]
Yeah libimobiledevice and it's various bits have been a pain to get installed on MacOS properly. They keep changing how it works. For the most park you can just install it directly via brew now and then delete the bits of the Makefile and it's related scripts that attempt to install it.

My suggestion is to move to Control Floor instead as it stabilizes. See https://github.com/DeviceFarmer/stf_ios_support/issues/94

Control Floor doesn't use libimobiledevice, because it's too flaky imo. It also doesn't use ZeroMQ. Or NodeJS. Essentially it uses 1/40th the amount of various stuffs used by stf_ios_support and STF.

**Comment by koltevinod1** [comment]
@nanoscopic how can we integrate control floor withh stf??

**Comment by koltevinod1** [comment]
@himanshunamdeo do you got solution for this issue??

**Comment by himanshunamdeo** [comment]
@koltevinod1 I wasn't able to figure out this one.
